### PR TITLE
Remove ie8/9 support

### PR DESCRIPTION
**Pull request by afc163**

### CODE REVIEW

**Comment by AmazingTurtle** [comment]
@afc163 I looked into ant.design upload component which is using rc-upload. They mentioned a prop `supportServerRender`. I tried to look it up and found this commit where you removed it. However you forgot to update the doc for `onReady` prop, see [here](https://github.com/react-component/upload/commit/b13cbddca580f8120ca602b831cdee54b5341216#diff-04c6e90faac2675aa89e2176d2eec7d8R61)

**Comment by afc163** [comment]
Could you help to update the doc?

**Comment by AmazingTurtle** [comment]
I can help with updating the docs in this repo.

Regarding ant.design docs: I can't find the correct repo for that. Perhaps is it the main [ant-design](https://github.com/ant-design/ant-design) repository?

**Comment by afc163** [comment]
image

**Pull request merged**
