### PR TITLE
Added openFileDialogOnEnter

### PR DESCRIPTION
**Pull request by DavidSichau**
@afc163 I am really sorry to bother you again, I made an error in the title. This pull request is similar to openFileDialogOnClick but this prevents to open the fileDialog on Enter.

This is useful if one for example wants to add drag and drop upload to a editor component, where the enter key is used for new lines.

### CODE REVIEW

**Comment by afc163** [comment]
😢 I made a mistake, it is so similar.

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
I think we can turn off keyboard behavior too when `openFileDialogOnClick` is `false`, no need to add another prop.

**Comment by DavidSichau** [comment]
Ok I will make the change.

**Comment by DavidSichau** [comment]
The changes are in the pull request: https://github.com/react-component/upload/pull/182

**Pull request closed without merging**
