### PR TITLE
fix: Changed openFileDialogOnClick to also prevent Enter key.

### PR DESCRIPTION
**Pull request by DavidSichau**
So this is the pull request with the requested changes. @afc163 I am sorry but I am not so familiar with github and somehow closed the other pull request.

### CODE REVIEW

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
Please run `npm run lint` in local first.

**Comment by DavidSichau** [comment]
@afc163 Thanks a lot for your patience. I fixed all linting issues in the code.

**Comment by afc163** [comment]
Released in `rc-upload@2.6.5`.

**Pull request merged**
